### ISSUE TITLE
Enhancement: enable an Admin to exclude specific event types (specified concepts) from an event taxonomy on import.

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-aggregator#107]
### Signe Laval request/user story
Would it be possible to create a rule that prevents events with the event type "Boxe" from being  imported into my CMS, i.e. exclude events with event type "Boxe". These events are being imported from co-motion (réservatech).

@sahalali analysis of this feature request is needed before adding to the roadmap. 
What changes are required?
- in the backend? (aggregator, api, ...)
- in the UI?

Test will be PASSED on success of excluding events from co-motion that include 'Boxe' event type from being imported into Signe Laval calendar.

**Comment by troughc** [comment]
@saumier can you please help with this question from Maude? Thanks.

**Comment by troughc** [comment]
This is fairly easy to do - it requires backend work only to exempt events having boxe additional type from coming into the CMS via  aggregator. TBD

**Comment by dev-aravind** [comment]
@troughc I've updated aggregator to prevent import of events with event type "Boxe". But during my testing I was not able to find an event with that particular type in co-motion.

**Comment by saumier** [comment]
@boxe event has passed

**Comment by troughc** [comment]
Closing this issue and will let Signe Laval know. Thanks!
