### ISSUE TITLE
For: Monday February 26th - Load a complete refresh of all entities for the acaligram user

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-aggregator#117]
Please load a complete refresh of events and entities from the acaligram user into the Production CMS. The weekend will give me time to review events to pass onto the client on Monday.

Note:  I will ask the client tomorrow whether we should keep uploading both the Event Tags and Event Types or just the Event Tags.

Many thanks.

**Comment by tammy-culture** [comment]
@sahalali Note: There is no need to remove any of the other users.  We can leave them as is and deal with them after the client's launch.

Thanks.

**Comment by tammy-culture** [comment]
@sahalali I just spoke with the client and they asked that we wait and hold off to do the acaligram refresh until Monday February 26th.  Please confirm that you received this message.

I updated the DUE DATE to February 26th.

Thanks.

**Comment by sahalali** [comment]
Okay, we will wait.
