### ISSUE TITLE
Load 2 websites from Console to CMS

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-aggregator#119]
Load the following 2 websites from Footlight Console into Production CMS:

- [ ] Pre-requisite is to add "startDate" to the reconciliation properties.

1.  https://www.culture3r.com/ (culture3r-com)
- [x] Artsdata: automatic minting of events 
- [x] Aggregator: load into CMS
- [x] Aggregator: set schedule for repeat loads

2. https://www.complexeculturelfelixleclerc.com/ (complexeculturelfelixleclerc-com)
- [x] Artsdata: automatic minting of events 
- [x] Aggregator: load into CMS
- [x] Aggregator: set schedule for repeat loads

**Comment by saumier** [comment]
First step is to add "startDate" to the reconciliation properties. This is a pre-requisite for automatically minting.  Second step is to code automatic minting of events for these 2 website. Third step is to load into CMS with Aggregator.

**Comment by saumier** [comment]
@sahalali Please read carefully my status **Status Mar 2, 2024** in https://docs.google.com/document/d/16OmxVUiwQsv6JrL_PuloKIjfkSdiJb8fyCMVcpccf_Q/edit#heading=h.shuzy3ds9r6j

I think should be unblocked, and you can continue with the next steps.

**Comment by tammy-culture** [comment]
@sahalali Also for many of the events the "Performing group/artist/event animator" is available in the Console as well.  It would be great if this information could follow into the Production CMS.  

Let me know if you need any screen shots.

Many thanks.

**Comment by sahalali** [comment]
@saumier 
1. The event types (additional type) are missing in the API response.

Here is the API used to fetch the list of events.

https://api.artsdata.ca/query?sparql=query_footlight_events&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/culture3r-com&limit=10&offset=0

**Comment by saumier** [comment]
@SuhailAliyar Good find. And thanks for the API link. It really makes it faster to look into the issue :-)

In the API response you can see the SPARQL, and it only returns keywords which we don't have for these 2 sites. I can add additionalType. Is there a JSON schema that you would like?

**Comment by saumier** [comment]
I propose the following

**Comment by sahalali** [comment]
I've updated the "sparql": ["https://github.com/culturecreates/artsdata-api/tree/main/app/services/sparqls/query_footlight_events.sparql"](https://github.com/culturecreates/artsdata-api/tree/main/app/services/sparqls/query_footlight_events.sparql),to return additionalType. I can then see the SPARQL is returning the events with additionalType. 
However, the API response still does not contain the additionalType. 
So I then tried updating the "frame": ["https://github.com/culturecreates/artsdata-api/tree/main/app/services/frames/event_footlight.jsonld"](https://github.com/culturecreates/artsdata-api/tree/main/app/services/frames/event_footlight.jsonld), however, it fails.

@saumier I will need your help to fix this.

**Comment by tammy-culture** [comment]
@sahalali I checked in the mapping file and I see that everything is complete.

1. Conference is already mapped in the file.
2. Culture Mauricie does not have ChildrensEvent so any ChildrensEvent will be mapped to Indéterminé in Culture Maurice.

FYI,  Indéterminé. menas unknown in French.

I hope this helps.

**Comment by tammy-culture** [comment]
@sahalali I understand that Culture3R and Felix-Leclerc are aggregated on the following schedule:
- Culture 3R - 3AM every Thursday
- Felix-Leclerc - 4AM every Thursday

Can we aggregate these sources twice a week, Monday and Thursday?

That wold be great.

Thanks.

**Comment by sahalali** [comment]
Scheduled the 3R and Felix aggregation every Monday and Thursday.

**Comment by tammy-culture** [comment]
@sahalali The client changed their mind and requested that Culture3R and Felix-Leclerc be aggregated on a daily basis.

**Comment by dev-aravind** [comment]
@tammy-culture I've updated both the workflows to be run daily.
