### ISSUE TITLE
Signe Laval: events from [co]motion

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-aggregator#120]
Maude from Signe Laval would like to know details about event series from co-motion that have multiple locations and were not imported from Artsdatata into the CMS. @saumier said taht there are a couple event series that have multiple locations.

Please provide the name of the event series, date/time and locationsif possible. Also the URL on comotion site. This info should be in artsdata.

**Comment by dev-aravind** [comment]
[Event 1](https://www.co-motion.ca/spectacles/pierre-luc-pomerleau-moqueur-polyglotte-2/#WebPage)

- Event Name: Pierre-Luc Pomerleau | Moqueur polyglotte, 
- Start Date: 2024-04-12T20:00:00-04:00
- End Date: 2024-11-15T20:00:00-05:00
- Locations: Salle André-Mathieu, Théâtre Marcellin-Champagnat

[Event 2](https://www.co-motion.ca/spectacles/theatre-pas-a-pas-talia-hallmona-theatre-fele-initiation-au-theatre-3-a-5-ans/#WebPage)

- Event Name: Théâtre pas à pas | Initiation au théâtre | 3 à 5 ans
- Start Date: 2024-05-05T11:00:00-04:00
- End Date: 2024-05-11T11:00:00-04:00
- Locations: Centre communautaire Laval-Ouest, Centres Communautaires St-Louis-de-Monfort

[Event 3](https://www.co-motion.ca/spectacles/initiation-au-theatre-dombres-theatre-dombres-4-6-ans/#WebPage)

- Event Name: Initiation au théâtre d’ombres | Théâtre d’ombres | 4-6 ans
- Start Date: 2024-05-05T10:00:00-04:00
- End Date: 2024-05-12T13:30:00-04:00
- Locations: Théâtre du Bout de l’île, Centres Communautaires St-Louis-de-Monfort

[Event 4](https://www.co-motion.ca/spectacles/marthe-laverdiere-fait-sont-show/#WebPage)

- Event Name: Marthe Laverdière | Fait son show 
- Start Date: 2024-04-23T20:00:00-04:00 
- End Date: 2024-10-13T20:00:00-04:00
- Locations: Théâtre Marcellin-Champagnat, Salle André-Mathieu

[Event 5](https://www.co-motion.ca/spectacles/philippe-audrey-larrue-st-jacques-enfant-du-siecle/#WebPage)

- Event Name: Philippe-Audrey Larrue-St-Jacques | Enfant du siècle
- Start Date: 2024-04-13T20:00:00-04:00
- End Date: 2025-01-28T20:00:00-05:00
- Locations: Théâtre Marcellin-Champagnat, Salle André-Mathieu

[Event 6](https://www.co-motion.ca/spectacles/le-petit-capuchon-rouge-theatre-3-ans-et/#WebPage)

- Event Name: Le Petit Capuchon rouge | Théâtre | 3 ans et + 
- Start Date: 2024-05-10T11:00:00-04:00
- End Date: 2024-05-13T10:00:00-04:00 
- Locations: Centre communautaire Laval-Ouest, Théâtre du Bout de l’île
