### ISSUE TITLE
Aggregator failing

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-aggregator#121]
Several events not getting loaded by Aggregator from Gatineau cloud (ville de Gatineau).  Repeating error is 
```
Batch 10 :: (3/4). Error while adding Event 
            {"uri":"https://calendrier.gatineau.cloud/calendrier/evenement.aspx?langue=fr-ca&id_evenement=44228"}TypeError: Cannot read properties of undefined (reading 'fr')
```
example events:
http://api.artsdata.ca/query?sparql=query_footlight_event_uri&uri=http://kg.footlight.io/resource/gatineau-cloud_44274&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/gatineau-cloud

http://api.artsdata.ca/query?sparql=query_footlight_event_uri&uri=http://kg.footlight.io/resource/gatineau-cloud_44228&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/gatineau-cloud

https://app.datadoghq.com/logs?query=&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAY82ymMhbo3BMAAAAAAAAAAYAAAAAEFZODJ5bU1oQUFDTjU5VF9pSTVIUmdBQQAAACQAAAAAMDE4ZjM2Y2EtNjg0My00MTBlLTlmYzktYzNkMTBkZjYxYjM5&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1714610878277&to_ts=1714611778277&live=true

**Comment by dev-aravind** [comment]
@saumier This issue is fixed and can be closed.
