### ISSUE TITLE
Rename Aggregator Workflows using exact Artsdata labels

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-aggregator#122]
The workflows are named based on the source website name. This is sometimes difficult to know which source from Artsdata is loaded for each workflow.

This issue is to rename the workflows to match the exact source name of the graph from Artsdata.

For example:
import-data-to-lepoint-in-footlight.yml should be renamed import-footlight-culturemauricie_lepointdevente-com.yml

The file naming convention:
--------------------
prefix:` import-`
group: `footlight` or `artsdata-orion` exactly as on Artsdata
dash: `-`
artifact: `culturemauricie_lepointdevente-com`  exactly as on Artsdata
extension: `.yml`

**Comment by dev-aravind** [comment]
@saumier The workflows are now renamed and the pull request is assinged to you. Please review it and let me know if you need any changes.
