### ISSUE TITLE
Acogeco aggregator is not returning images to client CMS

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-aggregator#125]
Images are not appearing in the Acogeco aggregator.  Acogeco aggregator is an API connection. This is blocking the client from publishing events in their D'ICI.CA calendar.

**Comment by saumier** [comment]
@dev This is an API import by Aggregator. Please look into this.

**Comment by saumier** [comment]
@tammy-culture Dev will look into this on our Sunday night (his Monday) and try to fix it for our Monday morning.

**Comment by dev-aravind** [comment]
@saumier Cogeco was part of our JSON-LD import via aggregator, it is fixed now.

**Comment by tammy-culture** [comment]
reviewed
