### ISSUE TITLE
upload events without locations

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-aggregator#126]
@sahalali is it possible to upload the following events from Artsdata to Signe Laval Footlight CMS? They do not have locations. Could they be uploaded without locations without too much work on your side?

This is a request from Signe Laval for this week. I'd like to know how much work it would take. I am looking into getting more clarity from Maude.

https://www.laval.ca/Pages/Fr/Calendrier/momo-5-7-rentree-culture-laval.aspx

https://www.laval.ca/Pages/Fr/Calendrier/recherche-activites.aspx#keywords=&advanced=true&isFree=all&clienteles=&categories=&subcategories=&tags=co-motion&sites=&startDate=2024-08-01&endDate=2024-09-29

https://www.laval.ca/Pages/Fr/Calendrier/recherche-activites.aspx#keywords=&advanced=true&isFree=all&clienteles=&categories=&subcategories=&tags=Musiques+du+monde&sites=&startDate=2024-09-03&endDate=2024-09-25

https://www.laval.ca/Pages/Fr/Calendrier/recherche-activites.aspx#keywords=&advanced=true&isFree=all&clienteles=&categories=&subcategories=&tags=Musiques+du+monde&sites=&startDate=2024-08-06&endDate=2026-06-20

https://www.laval.ca/Pages/Fr/Calendrier/recherche-activites.aspx#keywords=&advanced=true&isFree=all&clienteles=&categories=&subcategories=&tags=Apr%C3%A8s-midi+famille&sites=&startDate=2024-08-02&endDate=2024-08-18

https://www.laval.ca/Pages/Fr/Calendrier/recherche-activites.aspx#keywords=&advanced=true&isFree=all&clienteles=&categories=&subcategories=&tags=Ateliers+culturels&sites=&startDate=2024-09-03&endDate=2024-09-25

**Comment by troughc** [comment]
Here are the links to the events: 

https://artsdata-nebula-d1ec887e2637.herokuapp.com/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-jeudi-comotion-parazar.aspx%232024-09-20T00-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-battle-danse-senior.aspx%232024-09-26T23-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-humour-peggy-sue.aspx%232024-09-19T23-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-jeudi-comotion-naomi.aspx%232024-09-13T00-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-humour-rachelle-elie.aspx%232024-09-12T23-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-jeudi-comotion-raccoon.aspx%232024-09-06T00-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-humour-sam-vigneault.aspx%232024-09-05T23-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-jeudi-comotion-vendou.aspx%232024-08-30T00-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-jeudis-co-motion-fleurir.aspx%232024-08-29T23-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-battle-danse-junior.aspx%232024-08-22T23-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-humour-frais-jour.aspx%232024-08-16T00-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-jeudi-comotion-bibi-club.aspx%232024-08-15T23-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-humour-jean-michel-elie.aspx%232024-08-09T00-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-jeudi-comotion-greg-beaudin.aspx%232024-08-08T23-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-mix-dj-voyage-funktastique.aspx%232024-08-07T22-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-mix-dj-throwback-shorties.aspx%232024-08-09T22-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-mix-dj-voyage-funktastique.aspx%232024-08-07T22-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-mix-dj-super-plage.aspx%232024-08-10T22-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-vacances-flip-fabrique.aspx%232024-08-02T17-30

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-recital-magie.aspx%232024-08-11T20-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-crinoline-chapeaux.aspx%232024-08-18T20-00

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-entre-deux-artistique-kumpania.aspx%232024-09-03T15-30

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-entre-deux-artistique-paillettes-sans-yeux.aspx%232024-09-10T16-30

https://kg.artsdata.ca/entity?uri=https%3A%2F%2Fwww.laval.ca%2FPages%2FFr%2FCalendrier%2Fmomo-entre-deux-artistique-precedents.aspx%232024-09-17T16-00

**Comment by troughc** [comment]
Thank you @sahalali

**Comment by sahalali** [comment]
cc @saumier
