### ISSUE TITLE
Aggregator failed : github action upload-download version deprecated

### ISSUE THREAD

**Issue by sahalali** [culturecreates/footlight-aggregator#130]
The aggregator that imports [Shawinigan](https://github.com/culturecreates/footlight-aggregator/actions/workflows/import-data-to-shawinigan-in-footlight.yml) and [Cogeco](https://github.com/culturecreates/footlight-aggregator/actions/workflows/import-data-to-cogeco-in-footlight.yml) to the CMS has been failing for the past week.

**Comment by saumier** [comment]
@SuhailAliyar Please also remove the warnings for deprecated Node.js version.

**Comment by sahalali** [comment]
The warnings for deprecated versions of Node.js have been removed from all potential workflows.

**Comment by saumier** [comment]
@sahalali I still see 2 workflows with actions/checkout@v2.   Not sure how you missed them ;-). Actions are still reporting warnings about node.js version

**Comment by sahalali** [comment]
Fixed warning. 
The fix is alos applied to workflows on footlight-calendar-api and reconciliation-apis

**Comment by saumier** [comment]
@sahalali Thanks.
