### ISSUE TITLE
create recurring activity to check for errors in the aggregator

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-aggregator#132]
Please set up a (weekly?) recurring activity to check for errors in all aggregators and diagnose problems as they occur. 
Also report on status weekly in a daily standup

Also consider adding a notification for users so they know how many events were updated / created and by which aggregator. This aspect could be implemented in https://github.com/culturecreates/footlight-app/issues/827

**Comment by sahalali** [comment]
The aggregator log has been updated. The revised log now appears as follows:![Image](https://github.com/user-attachments/assets/b4ddf62c-31eb-4bb5-9f2a-32ab1da2500b)
: 


Let's create weekly aggregator reports by downloading filter logs from datadog. This will help us to go through the summary and if needed in detail as well.

Example: https://app.datadoghq.com/logs?query=service%3Afootlight-aggregator%20Import%20statistics&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1730184466062&to_ts=1730789266062&live=true

**Comment by sahalali** [comment]
@troughc We can notify users about the status of the aggregator run through the CMS by using the CMS API to send them a message after each run. This will ensure users are informed in CMS.
One point that is unclear to me is whether we should notify all admin users in the calendars about the aggregator run summary and the aggregator user. I believe we need to inform all admin users. It should be a summary message like the one in the attached screenshot.

**Comment by sahalali** [comment]
I set up a monitor in Datadog to notify admin@culturecreates.com if any aggregators finish running with at least one error.
![Image](https://github.com/user-attachments/assets/623a081a-4fee-481d-aa1b-8ec3778d35f9)

**Comment by troughc** [comment]
@sahalali comment from @saumier : Please add current practice to wiki and note location here. Thanks

**Comment by sahalali** [comment]
The notes are added to the [wiki](https://github.com/culturecreates/culture-creates-wiki/wiki/Footlight-Overview)

**Comment by troughc** [comment]
@sahalali what's next?

**Comment by sahalali** [comment]
I will preset the aggregator-run reports every week during the standup.
I think we can close this ticket as we have a plan.
