### ISSUE TITLE
gatineau cloud and many other aggregators not working

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-aggregator#133]
aville de gatineau is not sending new events to Tout Culture calendar since October 3.
https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events?page=1&order=desc&sortBy=metadata.createdAt&users=6483948a371b8f006491270f

Please also check other aggregators to make sure everything is working.

**Comment by sahalali** [comment]
I just reran the aggregator manually once and I can [see events](https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events?page=1&order=desc&sortBy=metadata.createdAt&users=6483948a371b8f006491270f) get imported to the CMS. 

I've verified that none of the workflow was an error before for this source. I verified it [here](https://github.com/culturecreates/footlight-aggregator/actions/workflows/import-footlight-gatineau-cloud.yml).


Can you check it once again @troughc

**Comment by troughc** [comment]
Need to re-run all other aggregators please

**Comment by troughc** [comment]
@sahalali I reviewed that the aggregators ran correctly in the CMS. Looks good. 
PASSED and closing this issue. 
thanks again!
