### ISSUE TITLE
Script to unlink CMS Events from Artsdata

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-aggregator#141]
## User Story

An event in Artsdata is always linked to an event form an external source. Sometimes this link can be a mistake, such as when the external website reuses the same URI for the same artists performing on a new future date, and the event is still linked to the previous Artsdata event.  The events in Artsdata are fixed by unlinking the Artsdata event from the external URI and minting a new Artsdata event. However, if there were any CMS events linked to the old event then these events in CMS should also be unlinked. 

## Solution

Events in Footlight CMS should be unlinked from Artsdata when the CMS startDate is different than linked event's Artsdata startDate.

The same daily script used to link CMS to Artsdata could be used to also unlink. 

Here is a SPARQL listing events with mismatched startDates.
https://kg.artsdata.ca/query/show?sparql=https://raw.githubusercontent.com/artsdata-stewards/artsdata-actions/main/queries/footlight_CMS_events_to_unlink.sparql

**Comment by saumier** [comment]
@sahalali Looks good but please rename the scripts and actions to represent the change. Before the names were all about "add-missing-artsdata-ids-to-cms-entities" but now the names of scripts and workflows are more about syncing by adding and removing Artsdata ids in the CMS. The name could be something like "sync-artsdata-ids-in-cms".

**Comment by sahalali** [comment]
Thanks for updating the code.
