### ISSUE TITLE
Aggregator: Support VirtualLocation

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-aggregator#18]
This event has a virtual location. 

http://kg.artsdata.ca/resource/K23-354
http://kg.footlight.io/resource/toutculture-ca_jam-trad-en-zoom-23167

Here is the query that should provide the input JSON to the Aggregator.
http://api.artsdata.ca/query?limit=100&sparql=query_footlight_events&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/signelaval-com

**Comment by sahalali** [comment]
@saumier Can you please add a live example of events having virtual Locations.

**Comment by saumier** [comment]
@dev-aravind  I couldn't find an existing example of a VirtualLocation. I need another day to create some examples.

**Comment by saumier** [comment]
@dev-aravind @sahalali I added a test VirtualLocation to this event http://api.artsdata.ca/query?sparql=query_footlight_event_uri&uri=http://kg.footlight.io/resource/maisondelaculture-ca_autres-evenements-disco-fever-experience-spectacle-benefice-fondation-mathieu-froment-savoie&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/maisondelaculture-ca

Let me know if you have any other questions.

**Comment by saumier** [comment]
@dev-aravind I can add the directive   "@container": "@type" to the JSON-LD Frame and it gives this results.  Is this better?

```
  "location": {
        "Place": "http://kg.artsdata.ca/resource/K2-197",
        "VirtualLocation": {
          "uri": "http://kg.footlight.io/resource/maisondelaculture-ca_autres-evenements-disco-fever-experience-spectacle-benefice-fondation-mathieu-froment-savoie#VirtualLocation",
          "url": "http://zoom.com/12345"
        }
      }
```

**Comment by saumier** [comment]
@dev-aravind I will add another example with a name using the standard @language container.

**Comment by saumier** [comment]
@dev-aravind I added another example. 
http://api.artsdata.ca/query?sparql=query_footlight_event_uri&uri=http://kg.footlight.io/resource/maisondelaculture-ca_humour-katherine-levac&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/maisondelaculture-ca

I also deployed the location  directive "@container": "@type" into production.

```
 "location": {
        "Place": "http://kg.artsdata.ca/resource/K2-197",
        "VirtualLocation": {
          "uri": "http://kg.footlight.io/resource/maisondelaculture-ca_humour-katherine-levac#VirtualLocation",
          "name": {
            "fr": "Test Virtual Location Name in @fr"
          },
          "url": "http://zoom.com/testroom"
        }
      },
```

**Comment by saumier** [comment]
@dev-aravind Please also check events without a Virtual Location which now give the updated structure:
http://api.artsdata.ca/query?sparql=query_footlight_events&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/maisondelaculture-ca


```
 "location": {
        "Place": "http://kg.artsdata.ca/resource/K2-197"
      }

```

**Comment by saumier** [comment]
@saumier Reminder to delete the test virtual events
https://console.footlight.io/events/footlight%3Amaisondelaculture-ca_autres-evenements-disco-fever-experience-spectacle-benefice-fondation-mathieu-froment-savoie

**Comment by saumier** [comment]
@dev-aravind Please update me on the progress.  Our client Maude, at Signé Laval, reported today that none of the places were imported with the weekly import. I am assuming this is because of the updated structure. So we will need to re-run the import once you have fixed the code.

**Comment by dev-aravind** [comment]
@saumier It's fixed now. Please re-run the imports and let me know if there are any issues.

**Comment by saumier** [comment]
@dev-aravind @sahalali I noticed that events now have blank virtual locations. This is a bug. 

Footlight API: https://api.footlight.io/events/64f95d027d6aa80064357035
has  "eventAttendanceMode": "MixedEventAttendanceMode"

This shows up in the event list with an extra "|" after the place name, and in the event details the fields for Virtual location url and name appear on the left side but are empty.

**Comment by dev-aravind** [comment]
@saumier I did a quick fix on it just now. If you re run the aggregator the empty the empty virtualLocations should be gone.

**Comment by saumier** [comment]
@dev-aravind The virtual location urls are not getting loaded.

## Example 1 - url and name
Event Katherine Levac should have the url http://zoom.com/testroom for the virtual location 
https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/64af64493c19fa0064e76db6

Current behaviour: both virtual location name and url are empty

Expected behaviour: virtual location name should be "Test Virtual Location Name in @fr" and url should be "http://zoom.com/testroom" 

Artsdata 
http://api.artsdata.ca/query?sparql=query_footlight_event_uri&uri=http://kg.footlight.io/resource/maisondelaculture-ca_humour-katherine-levac&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/maisondelaculture-ca

```
 "location": {
        "Place": "http://kg.artsdata.ca/resource/K2-197",
        "VirtualLocation": {
          "uri": "http://kg.footlight.io/resource/maisondelaculture-ca_humour-katherine-levac#VirtualLocation",
          "name": {
            "fr": "Test Virtual Location Name in @fr"
          },
          "url": "http://zoom.com/testroom"
        }
      }
```

## Example 2 - url only
Event Disco Fever Experience
https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/64af644a3c19fa0064e76de9

Current behaviour: both virtual location name and url are empty

Expected behaviour: virtual location url should be "http://zoom.com/12345" 

Artsdata
http://api.artsdata.ca/query?sparql=query_footlight_event_uri&uri=http://kg.footlight.io/resource/maisondelaculture-ca_autres-evenements-disco-fever-experience-spectacle-benefice-fondation-mathieu-froment-savoie&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/maisondelaculture-ca

```
 "location": {
        "Place": "http://kg.artsdata.ca/resource/K2-197",
        "VirtualLocation": {
          "uri": "http://kg.footlight.io/resource/maisondelaculture-ca_autres-evenements-disco-fever-experience-spectacle-benefice-fondation-mathieu-froment-savoie#VirtualLocation",
          "url": "http://zoom.com/12345"
        }
      }
```

**Comment by dev-aravind** [comment]
@saumier The virtualLocation name issue was solved when I ran the aggregator again, and I've done a hotfix for the URI issue. Thanks for pointing that out.

**Comment by saumier** [comment]
Looks good. I removed sample data. Closing.
