### ISSUE TITLE
Aggregator support for type array - Blue Jean Bleu

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-aggregator#19]
Artsdata returned the following data for Blue Jean Bleu organization

http://api.artsdata.ca/query?adid=K10-580&format=json&frame=ranked_org_person_footlight&sparql=ranked_org_person_footlight

```
{
  "status": "success",
  "meta": {
    "sparql": "ranked_org_person_footlight",
    "frame": "ranked_org_person_footlight",
    "limit": "10",
    "offset": "0",
    "adid": "K10-580",
    "format": "json"
  },
  "data": [
    {
      "uri": "http://kg.artsdata.ca/resource/K10-580",
      "type": [
        "Organization",
        "MusicGroup"
      ],
      "name": {
        "fr": "Bleu Jeans Bleu",
        "en": "Bleu Jeans Bleu"
      },
      "sameAs": [
        {
          "uri": "http://kg.artsdata.ca/resource/K10-580"
        }
      ],
      "url": {
        "uri": "http://www.bleujeansbleu.com/"
      },
      "contactPoint": null
    }
  ]
}
```

**Comment by sahalali** [comment]
@saumier Lets discuss this during todays standup.

**Comment by sahalali** [comment]
As we discussed during the standup, the type with an array should not break the aggregator. I think we can remove type from organization (for now) before passing to footlight.

**Comment by dev-aravind** [comment]
@saumier I couldn't fetch the organization that you mentioned in the description from artsdata to aggregator

**Comment by dev-aravind** [comment]
@saumier The coding part of this issue was resolved in #572 but as the event was last modified by @troughc, aggregator cannot modify it. This can be fixed if @troughc could run the co-motion aggregator from her footlight account.

**Comment by saumier** [comment]
Here is the link http://staging.cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/644139d77a2993006450b3bb

**Comment by saumier** [comment]
@dev-aravind I ran into a bug "Request failed with status code 400 " running the aggregator. So I am blocked trying to test this issue.

http://localhost:3033/events/sync?footlight-base-url=https%3A%2F%2Fstaging.api.cms.footlight.io&calendar-id=signe-laval&source=http%3A%2F%2Fkg.artsdata.ca%2Fculture-creates%2Ffootlight%2Fco-motion-ca&batch-size=5&mapping-url=http%3A%2F%2Fraw.githubusercontent.com%2Fculturecreates%2Ffootlight-aggregator%2Fmain%2Fdata%2Fco-motion-cms-mapping.json


```
Fetching taxonomies
Unable to fetch URL https://staging.api.cms.footlight.io/taxonomy?include-concepts=true&taxonomy-class=EVENT Error ::, AxiosError: Request failed with status code 400
[Nest] 17769  - 09/12/2023, 10:53:34 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'map')
```

**Comment by saumier** [comment]
@dev-aravind @sahalali Can we add a single test in Aggregator for this fix? I would like to see a test with the JSON input for the Organization (we can Use Blue Jean Bleu as a text fixture) and the expected output that will be sent to CMS API.  

The input will include
```
...
"type": [
        "Organization",
        "MusicGroup"
      ]
```
The expected output will have

```
...
"type": "Organization"
```

We don't need to add all cases now, but it would be much easier to test that running the aggregator which takes a long time.

Let me know what you think.

**Comment by dev-aravind** [comment]
@saumier The unit tests are up to be merged with production now.

**Comment by saumier** [comment]
@dev-aravind Looks good except I am wondering why you didn't add  `--detectOpenHandles` to the package.json? Is there a reason?

This line is printing in my console each time I run the tests:
Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?

**Comment by saumier** [comment]
@dev-aravind I am closing this issue but please reply to my question above. Thx.

**Comment by dev-aravind** [comment]
@saumier We were actually not using detectOpenHandles in the OpenAPI unit tests. This is caused by the async operations that are running in the test. I've actually tried to fix this issue when we had the problem where the Open-API unit tests were failing in staging and decided to not include --detectOpenHandles as I suspected it was breaking change.
