### ISSUE TITLE
Aggregator event type mapping

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-aggregator#29]
As an admin, I can map events from a website that I import with the Aggregator to my calendar's event type taxonomy. This saves me the trouble of manually editing the events.

Here is an example of mapping keywords from Ville de Gatineau to Tout Culture's event type taxonomy.
https://docs.google.com/spreadsheets/d/15ri2MyKHGsbUcK8Kb83BijXMKkMZCfWjxcCK65Cmu_I/edit#gid=0

**Comment by sahalali** [comment]
Updated aggregator scheduler scripts with mapping URLs.

**Comment by saumier** [comment]
This looks great. My spot checks are working. I'll adjust the audience mapping, but since that is a data driven, I will close this issue.
