### ISSUE TITLE
Facebook link bug

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-aggregator#41]
The facebook links are getting duplicated in the sameAs property.  

Example input to Aggregator:
http://api.artsdata.ca/query?sparql=query_footlight_event_uri&uri=http://kg.footlight.io/resource/signelaval-com_l-infiniment-petit-sous-la-loupe&frame=event_footlight&format=json&source=http://kg.artsdata.ca/culture-creates/footlight/signelaval-com

Example: event created in CMS:
https://api.footlight.io/events/644139ad7a2993006450a939

**Comment by dev-aravind** [comment]
I tested the aggregator API to sync the events and also the admin-api functions connected to that API, but was not able to reproduce that bug. However if you managed to sync the event that has the duplicated sameAs property, the duplicated data will be discarded and the event would be updated properly in our DB. 

So we can fix the events with the duplicated data by syncing it with arts data. As we could not reproduce the bug, my suggestion is that we keep a look out for the next time this bug occurs and retrace our steps to fix this issue. What do you think? @saumier

**Comment by saumier** [comment]
I haven't see this appear recently, so I will close for now.

**Comment by saumier** [comment]
Today I removed the duplicate facebook links from sameAs using old CMS. Next week I will check to see if the Aggregator created another duplicate.

**Comment by saumier** [comment]
Closing as I did not see more duplicate Facebook links.
