### ISSUE TITLE
Aggregator mapping data

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-aggregator#55]
The data files should be published as they appear in the main branch. The idea of a "data" branch was introduced to facilitate using GitHub pages for making files in a private repo available via url. But this approach is prone to errors because it requires an extra step of publishing a branch and is difficult to trace.

A better solution is to link directly to the URL of the raw data JSON file.  The GitHub Pages option can be deactivated and the data branch deleted.

Related issue https://github.com/culturecreates/footlight-aggregator/issues/51

**Comment by saumier** [comment]
@sahalali Please update the URLs in the workflows to point to the raw data JSON.  When I look in the workflows they still point to -m https://culturecreates.github.io/footlight-aggregator/data/salle-odyssee-cms-mapping.json but they should point to https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/data/salle-odyssee-cms-mapping.json

**Comment by sahalali** [comment]
Updated github action scripts.
Deleted the brach "data".
Deleted github pages.
Tested Aggregator running with the new URLs

**Comment by saumier** [comment]
@sahalali Great. Thx. I think this setup is simpler and easier to use. In the future please share your thoughts if you see any issues using raw Github files. I'll close this issue now.
