### ISSUE TITLE
Workflow linter errors

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-aggregator#81]
How to fix these linter errors? The scripts are running ok. Its only the errors in the IDE.

<img width="1276" alt="Screenshot 2023-12-14 at 10 14 03 PM" src="https://github.com/culturecreates/footlight-aggregator/assets/419491/3ad30dc0-8b18-48d8-8a21-cb9b3c84a194">

**Comment by sahalali** [comment]
@saumier I am using Webstorm IDE. I don't see any issue with my IDE. 
@dev-aravind Can you check if you face this issue in your VS code IDE?
Let see if this is a common issue in VS code and happening to others as well.

**Comment by saumier** [comment]
@dev-aravind I am also using github-actions extension.

![Image](https://github.com/culturecreates/footlight-aggregator/assets/419491/38f5af31-a492-497a-a919-ab4f3f4a0cdd)

**Comment by dev-aravind** [comment]
@saumier List of the extensions on my machine :



![Image](https://github.com/culturecreates/footlight-aggregator/assets/132546883/711e8dbe-a0a6-4f9d-a4a8-468c71f99a2a)
